### PR TITLE
Merge commits that we actually use into default branch

### PR DESCRIPTION
**Pull request by ala-ableton**
@mak-ableton, @nre-ableton, @toh-ableton: please review, thanks!

FYI: I will make the `verboten` check non-required to be able to merge this PR.

### CODE REVIEW

**Review by nre-ableton — APPROVED** [review]
LGTM 👍

**Comment by ala-ableton** [comment]
@mak-ableton, @nre-ableton, @toh-ableton: I've updated this PR after merging #7. Please have another look, thanks!

**Comment by nre-ableton** [comment]
Very biased but still LGTM 😅

**Review by nre-ableton — APPROVED** [review]

**Review by toh-ableton — APPROVED** [review]
lgtm. Do you have a corresponding live branch with CI?

**Comment by ala-ableton** [comment]
@toh-ableton not yet. That's why I didn't merge yet :sweat_smile:

**Pull request merged**
