### PR TITLE
Update our fork to v0.5

### PR DESCRIPTION
**Pull request by ala-ableton**
Update our fork to the [`v0.5` tag of upstream](https://github.com/cucumber/cucumber-cpp/tree/v0.5).

### CODE REVIEW

**Comment by toh-ableton** [comment]
Seems about right to me if you get it to build :)

**Comment by mak-ableton** [comment]
I agree with Tobi: Looks reasonable. :shipit: if it works!

**Comment by nre-ableton** [comment]
This doesn't look right to me. 2fc4497 and 609bb41 are not on `ableton-master`. I would only expect to see upstream commits in a PR like this.

**Review by nre-ableton — APPROVED** [review]
(Talked to @ala-ableton IRL, LGTM 👍 )

**Comment by ala-ableton** [comment]
@mak-ableton, @toh-ableton: I talked to @nre-ableton, and we decided to make this PR only about fast-forwarding `ableton-master` (the default branch of this repo) to `v0.5`. I'll then resurrect #4 to merge the commits that we are actually currently using (from the tags `ableton-initial-migration` and `build-with-xcode-10`) into the default branch.

**Pull request merged**
