### PR TITLE
Bring `upstream-main` up to date with the main fork

### PR DESCRIPTION
**Pull request by rkk-ableton**

### CODE REVIEW

**Comment by ala-ableton** [comment]
@src-ableton what is this `upstream-main` branch? That's not the default branch of this repository.

**Comment by rkk-ableton** [comment]
I created `upstream-main` in order to have a branch which I can commit to in case I need to patch the update.

**Comment by ala-ableton** [comment]
I'm pretty sure you wouldn't make a new branch in `build-system` and update `live.git` to point to that new branch. Here it's the same. There is already a default branch (`ableton-master`) and that's the only branch `live.git` should point to.

**Comment by rkk-ableton** [comment]
I see, is there a documented process for updating submodules we maintain?

My goal was to have a way to test the changes on CI without merging to `ableton-master`.

**Comment by ala-ableton** [comment]
I'm sorry, I think I misunderstood your original intent. I thought you wanted to make `live.git`'s `master` branch point to 0fedc316dc09c0e91fd23dbb4a5c6153f3e29cb6 (the merge commit of this PR, which was not on `ableton-master` when I wrote my first comment). Using an intermediate branch (here `upstream-main`) where the upstream changes are merged, then fast-forwarding the default branch (here `ableton-master`) to that intermediate branch after the CI run, makes a lot of sense. I guess I was confused by the use of a PR to create that merge commit.

**Pull request merged**
